### ISSUE TITLE
Swagger docs inaccurate / outdated

### ISSUE THREAD

**Issue by kitajchuk** [jambonz/jambonz-api-server#61]
Something the webapp refresh has illuminated is that the Swagger docs for the API server have quite a bit of inaccuracies compared to actual DTO responses received on the client as well as at least one endpoint missing from the documentation entirely. It would be worth combing over the Swagger yaml and getting the documentation up to date. This issue may overlap with this one: https://github.com/jambonz/jambonz-api-server/issues/13 and we might be able to consolidate and close the older issue 🤔.

**Todo for this issue:**

- [ ] Create a "completed", comprehensive list of what is known to be missing or inaccurate in the Swagger docs

**Comprehensive (incomplete) list of what is missing/inaccurate in Swagger docs:**

- [ ] The API for `Accounts/:account_sid/Applications` is in use for the webapp but missing entirely from the docs
- [ ] The `SmppGateways/SipGateways` show `inbound/outbound` as boolean but they are actually binary: `1/0`
- [ ] The `SpeechCredential` shows `use_for_tts/use_for_stt` as boolean but they are also binary: `1/0`
- [ ] The `RecentCalls` shows  the field as `sip_call_id` but it is actually `sip_callid` as returned from the API
- [ ] The :GET `RecentCall` and `RecentCall` pcap toggles have the same ID and both toggle open at the same time
- [ ] ...

**Comment by rjp44** [comment]
Please add `PhoneNumbers` which is at present undocumented to that list.
